### ISSUE TITLE
RTKLIB qt build

### ISSUE THREAD

**Issue by pepijntje02** [rtklibexplorer/RTKLIB#127]
Hi,

There is an error when installing the GUI part of the code.

```
git clone https://github.com/rtklibexplorer/RTKLIB.git
cd RTKLIB/app/qtapp
qmake
make
```

The error I got is:

```bash
navimain.cpp: In member function ‘void MainWindow::LoadOpt()’:
navimain.cpp:2425:12: error: ‘struct prcopt_t’ has no member named ‘maxgdop’
     PrcOpt.maxgdop = settings.value("prcopt/maxgdop", 30.0).toDouble();
            ^~~~~~~
navimain.cpp:2426:70: error: incompatible types in assignment of ‘double’ to ‘double [2]’
     PrcOpt.maxinno = settings.value("prcopt/maxinno", 30.0).toDouble();
                                                                      ^
navimain.cpp: In member function ‘void MainWindow::SaveOpt()’:
navimain.cpp:2639:48: error: ‘struct prcopt_t’ has no member named ‘maxgdop’
     settings.setValue("prcopt/maxgdop", PrcOpt.maxgdop);
                                                ^~~~~~~
navimain.cpp:2640:55: error: use of deleted function ‘QVariant::QVariant(void*)’
     settings.setValue("prcopt/maxinno", PrcOpt.maxinno);
                                                       ^
In file included from /usr/include/arm-linux-gnueabihf/qt5/QtCore/qsettings.h:44,
                 from /usr/include/arm-linux-gnueabihf/qt5/QtCore/QSettings:1,
                 from navimain.cpp:38:
/usr/include/arm-linux-gnueabihf/qt5/QtCore/qvariant.h:489:12: note: declared here
     inline QVariant(void *) Q_DECL_EQ_DELETE;
            ^~~~~~~~
make[1]: *** [Makefile:951: navimain.o] Error 1
make[1]: Leaving directory '/home/pi/Documents/RTKLIB/app/qtapp/rtknavi_qt'
make: *** [Makefile:78: sub-rtknavi_qt-make_first] Error 2
``` 

I try to install this on an raspberry pi and I have the following packages installed:

```
libpoppler-qt5-1/oldstable,now 0.71.0-5 armhf [installed,automatic]
libqt5concurrent5/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
libqt5core5a/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
libqt5dbus5/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
libqt5gui5/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
libqt5network5/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
libqt5opengl5/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
libqt5opengl5-dev/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
libqt5printsupport5/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
libqt5serialport5/oldstable,now 5.11.3-2 armhf [installed]
libqt5serialport5-dev/oldstable,now 5.11.3-2 armhf [installed]
libqt5sql5/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
libqt5sql5-sqlite/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
libqt5svg5/oldstable,now 5.11.3-2 armhf [installed,automatic]
libqt5test5/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
libqt5widgets5/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
libqt5x11extras5/oldstable,now 5.11.3-2 armhf [installed,automatic]
libqt5xml5/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
qt5-default/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed]
qt5-gtk-platformtheme/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed,automatic]
qt5-qmake/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed]
qt5-qmake-bin/oldstable,now 5.11.3+dfsg1-1+rpi1+deb10u4 armhf [installed]
qt5-style-plugins/oldstable,now 5.0.0+git23.g335dbec-2+rpt1 armhf [installed,automatic]
qt5ct/oldstable,now 0.37-1+rpt1 armhf [installed,automatic]
```

Does someone know how to fix this?

_edit:_

I also tried to install this on Ubuntu (WSL) but got the same error.

**Comment by StraxAdNav** [comment]
It was introduced with 6fcf246d9137ac55ffacc2fc13f60b953a8c34a7
Should be easy to fix

**Comment by pepijntje02** [comment]
Thank you for your comment. I looked at the change log but I could not found a change in the qt5 files. C is not my main programming language, therefore it is not an easy fix for me. But if you can give me some more hints then I can try to fix it, maybe a good moment to start learning C.

**Comment by HamishB** [comment]
The first changelog entry of https://github.com/rtklibexplorer/RTKLIB/commit/6fcf246d9137ac55ffacc2fc13f60b953a8c34a7 is
- Remove GDOP threshold config param

the compile-time error is:
 `error: ‘struct prcopt_t’ has no member named ‘maxgdop’`

so the removal of max GDOP broke `make sub-rtknavi_qt` and `make sub-rtkpost_qt`.

specifically it was removed from src/rtklib.h (line 1026) but these files / line numbers still reference it:
```
rtkpost_qt/postmain.cpp:948:    prcopt.maxgdop  =RejectGdop;
rtkpost_qt/postopt.cpp:718:    RejectGdop->setValue(prcopt.maxgdop);
rtkpost_qt/postopt.cpp:868:    prcopt.maxgdop = RejectGdop->value();

rtknavi_qt/navimain.cpp:2425:    PrcOpt.maxgdop = settings.value("prcopt/maxgdop", 30.0).toDouble();
rtknavi_qt/navimain.cpp:2639:    settings.setValue("prcopt/maxgdop", PrcOpt.maxgdop);
rtknavi_qt/naviopt.cpp:472:    RejectGdop->setValue(PrcOpt.maxgdop);
rtknavi_qt/naviopt.cpp:600:    PrcOpt.maxgdop = RejectGdop->value();
rtknavi_qt/naviopt.cpp:785:    RejectGdop->setValue(prcopt.maxgdop);
rtknavi_qt/naviopt.cpp:1000:    prcopt.maxgdop = RejectGdop->value();
```

the other programs build successfully if make is invoked manually, bypassing the two programs that break:
`make sub-rtkget_qt sub-rtkplot_qt sub-rtklaunch_qt sub-srctblbrows_qt sub-strsvr_qt sub-rtkconv_qt`


thanks,
Hamish

**Comment by drf5n** [comment]
If I comment out the lines in https://github.com/rtklibexplorer/RTKLIB/issues/127#issuecomment-1296463732

and compile on Mac with a QT6 homebrew I run into a couple further errors:

```
navimain.cpp:2426:20: error: array type 'double[2]' is not assignable
    PrcOpt.maxinno = settings.value("prcopt/maxinno", 30.0).toDouble();
    ~~~~~~~~~~~~~~ ^
navimain.cpp:2640:41: error: attempt to use a deleted function
    settings.setValue("prcopt/maxinno", PrcOpt.maxinno);
                                        ^
/usr/local/lib/QtCore.framework/Headers/qvariant.h:199:5: note: 'QVariant<double *, false>' has been explicitly marked deleted here
    QVariant(T) = delete;
    ^
navimain.cpp:2662:37: error: attempt to use a deleted function
    settings.setValue("solopt/sep", SolOpt.sep);
                                    ^

/usr/local/lib/QtCore.framework/Headers/qvariant.h:199:5: note: 'QVariant<char *, false>' has been explicitly marked deleted here
    QVariant(T) = delete;
    ^
2 warnings and 3 errors generated.
```

This diff didn't quite get me to working:

```
diff --git a/app/qtapp/rtkget_qt/getmain.cpp b/app/qtapp/rtkget_qt/getmain.cpp
index cb0a97f..4d1bfa9 100644
--- a/app/qtapp/rtkget_qt/getmain.cpp
+++ b/app/qtapp/rtkget_qt/getmain.cpp
@@ -450,7 +450,7 @@ void MainForm::BtnTime1Click()
     QDateTime time(dateTime1->dateTime());
     gtime_t t1;
 
-    t1.time = static_cast<time_t>(time.toTime_t()); t1.sec = time.time().msec() / 1000;
+    t1.time = static_cast<time_t>(time.toSecsSinceEpoch()); t1.sec = time.time().msec() / 1000;
     timeDialog->Time = t1;
     timeDialog->exec();
 }
@@ -460,7 +460,7 @@ void MainForm::BtnTime2Click()
     QDateTime time(dateTime2->dateTime());
     gtime_t t2;
 
-    t2.time = static_cast<time_t>(time.toTime_t()); t2.sec = time.time().msec() / 1000;
+    t2.time = static_cast<time_t>(time.toSecsSinceEpoch()); t2.sec = time.time().msec() / 1000;
     timeDialog->Time = t2;
     timeDialog->exec();
 }
diff --git a/app/qtapp/rtknavi_qt/navimain.cpp b/app/qtapp/rtknavi_qt/navimain.cpp
index 6038374..7bab73b 100644
--- a/app/qtapp/rtknavi_qt/navimain.cpp
+++ b/app/qtapp/rtknavi_qt/navimain.cpp
@@ -2422,8 +2422,8 @@ void MainWindow::LoadOpt(void)
     PrcOpt.elmaskhold = settings.value("prcopt/elmaskhold", 0.0).toDouble();
     PrcOpt.thresslip = settings.value("prcopt/thresslip", 0.05).toDouble();
     PrcOpt.maxtdiff = settings.value("prcopt/maxtdiff", 30.0).toDouble();
-    PrcOpt.maxgdop = settings.value("prcopt/maxgdop", 30.0).toDouble();
-    PrcOpt.maxinno = settings.value("prcopt/maxinno", 30.0).toDouble();
+    //PrcOpt.maxgdop = settings.value("prcopt/maxgdop", 30.0).toDouble();
+    PrcOpt.maxinno[0] = settings.value("prcopt/maxinno", 30.0).toDouble();
     PrcOpt.syncsol = settings.value("prcopt/syncsol", 0).toInt();
     ExSats = settings.value("prcopt/exsats", "").toString();
     PrcOpt.navsys = settings.value("prcopt/navsys", SYS_GPS).toInt();
@@ -2445,8 +2445,8 @@ void MainWindow::LoadOpt(void)
     SolOpt.timef = settings.value("solopt/timef", 1).toInt();
     SolOpt.timeu = settings.value("solopt/timeu", 3).toInt();
     SolOpt.degf = settings.value("solopt/degf", 0).toInt();
-    s = settings.value("solopt/sep", " ").toString();
-    strcpy(SolOpt.sep, qPrintable(s));
+   // s = settings.value("solopt/sep", " ").toString();
+   // strcpy(SolOpt.sep, qPrintable(s));
     SolOpt.outhead = settings.value("solop/outhead", 0).toInt();
     SolOpt.outopt = settings.value("solopt/outopt", 0).toInt();
     SolOpt.outvel = settings.value("solopt/outvel", 0).toInt();
@@ -2636,8 +2636,8 @@ void MainWindow::SaveOpt(void)
     settings.setValue("prcopt/elmaskhold", PrcOpt.elmaskhold);
     settings.setValue("prcopt/thresslip", PrcOpt.thresslip);
     settings.setValue("prcopt/maxtdiff", PrcOpt.maxtdiff);
-    settings.setValue("prcopt/maxgdop", PrcOpt.maxgdop);
-    settings.setValue("prcopt/maxinno", PrcOpt.maxinno);
+    //settings.setValue("prcopt/maxgdop", PrcOpt.maxgdop);
+    settings.setValue("prcopt/maxinno", PrcOpt.maxinno[0]);
     settings.setValue("prcopt/syncsol", PrcOpt.syncsol);
     settings.setValue("prcopt/exsats", ExSats);
     settings.setValue("prcopt/navsys", PrcOpt.navsys);
@@ -2659,7 +2659,7 @@ void MainWindow::SaveOpt(void)
     settings.setValue("solopt/timef", SolOpt.timef);
     settings.setValue("solopt/timeu", SolOpt.timeu);
     settings.setValue("solopt/degf", SolOpt.degf);
-    settings.setValue("solopt/sep", SolOpt.sep);
+   // settings.setValue("solopt/sep", SolOpt.sep);
     settings.setValue("solopt/outhead", SolOpt.outhead);
     settings.setValue("solopt/outopt", SolOpt.outopt);
     settings.setValue("solopt/outvel", SolOpt.outvel);
diff --git a/app/qtapp/rtknavi_qt/naviopt.cpp b/app/qtapp/rtknavi_qt/naviopt.cpp
index 6aea16b..d3294ad 100644
--- a/app/qtapp/rtknavi_qt/naviopt.cpp
+++ b/app/qtapp/rtknavi_qt/naviopt.cpp
@@ -469,8 +469,8 @@ void OptDialog::GetOpt(void)
     ElMaskAR->setValue(PrcOpt.elmaskar * R2D);
     ElMaskHold->setValue(PrcOpt.elmaskhold * R2D);
     MaxAgeDiff->setValue(PrcOpt.maxtdiff);
-    RejectGdop->setValue(PrcOpt.maxgdop);
-    RejectThres->setValue(PrcOpt.maxinno);
+//    RejectGdop->setValue(PrcOpt.maxgdop);
+    RejectThres->setValue(PrcOpt.maxinno[0]);
     SlipThres->setValue(PrcOpt.thresslip);
     NumIter->setValue(PrcOpt.niter);
     SyncSol->setCurrentIndex(PrcOpt.syncsol);
@@ -597,8 +597,8 @@ void OptDialog::SetOpt(void)
     PrcOpt.elmaskar = ElMaskAR->value() * D2R;
     PrcOpt.elmaskhold = ElMaskHold->value() * D2R;
     PrcOpt.maxtdiff = MaxAgeDiff->value();
-    PrcOpt.maxgdop = RejectGdop->value();
-    PrcOpt.maxinno = RejectThres->value();
+//    PrcOpt.maxgdop = RejectGdop->value();
+    PrcOpt.maxinno[0] = RejectThres->value();
     PrcOpt.thresslip = SlipThres->value();
     PrcOpt.niter = NumIter->value();
     PrcOpt.syncsol = SyncSol->currentIndex();
@@ -782,8 +782,8 @@ void OptDialog::LoadOpt(const QString &file)
     ElMaskAR->setValue(prcopt.elmaskar * R2D);
     ElMaskHold->setValue(prcopt.elmaskhold * R2D);
     MaxAgeDiff->setValue(prcopt.maxtdiff);
-    RejectGdop->setValue(prcopt.maxgdop);
-    RejectThres->setValue(prcopt.maxinno);
+//    RejectGdop->setValue(prcopt.maxgdop);
+    RejectThres->setValue(prcopt.maxinno[0]);
     SlipThres->setValue(prcopt.thresslip);
     NumIter->setValue(prcopt.niter);
     SyncSol->setCurrentIndex(prcopt.syncsol);
@@ -997,8 +997,8 @@ void OptDialog::SaveOpt(const QString &file)
     prcopt.elmaskar = ElMaskAR->value() * D2R;
     prcopt.elmaskhold = ElMaskHold->value() * D2R;
     prcopt.maxtdiff = MaxAgeDiff->value();
-    prcopt.maxgdop = RejectGdop->value();
-    prcopt.maxinno = RejectThres->value();
+//    prcopt.maxgdop = RejectGdop->value();
+    prcopt.maxinno[0] = RejectThres->value();
     prcopt.thresslip = SlipThres->value();
     prcopt.niter = NumIter->value();
     prcopt.syncsol = SyncSol->currentIndex();
diff --git a/app/qtapp/rtkpost_qt/kmzconv.cpp b/app/qtapp/rtkpost_qt/kmzconv.cpp
index 7a9829e..3137f7c 100644
--- a/app/qtapp/rtkpost_qt/kmzconv.cpp
+++ b/app/qtapp/rtkpost_qt/kmzconv.cpp
@@ -103,8 +103,10 @@ void ConvDialog::BtnConvertClick()
     if (TimeSpan->isChecked()) {
         QDateTime start(dateTime1->dateTime());
         QDateTime end(dateTime2->dateTime());
-        ts.time = start.toTime_t(); ts.sec = start.time().msec() / 1000;
-        te.time = end.toTime_t(); te.sec = end.time().msec() / 1000;
+        //ts.time = start.toTime_t(); ts.sec = start.time().msec() / 1000;
+        //te.time = end.toTime_t(); te.sec = end.time().msec() / 1000;
+        ts.time = start.toSecsSinceEpoch(); ts.sec = start.time().msec() / 1000;
+        te.time = end.toSecsSinceEpoch(); te.sec = end.time().msec() / 1000;
 	}
 
     if (AddOffset->isChecked()) {
@@ -215,7 +217,7 @@ void ConvDialog::UpdateOutFile(void)
 
     if (InputFile_Text == "") return;
     QFileInfo fi(InputFile_Text);
-    if (fi.suffix() == NULL) return;
+    if (fi.suffix().isNull()) return;
     InputFile_Text = QDir::toNativeSeparators(fi.absolutePath() + "/" + fi.baseName());
     InputFile_Text += FormatGPX->isChecked() ? ".gpx" : (Compress->isChecked() ? ".kmz" : ".kml");
     OutputFile->setText(InputFile_Text);
diff --git a/app/qtapp/rtkpost_qt/postmain.cpp b/app/qtapp/rtkpost_qt/postmain.cpp
index 65d7bc1..4d915d4 100644
--- a/app/qtapp/rtkpost_qt/postmain.cpp
+++ b/app/qtapp/rtkpost_qt/postmain.cpp
@@ -489,10 +489,10 @@ void MainForm::BtnExecClick()
         OutputFile_Text.contains(".gnav",Qt::CaseInsensitive)||
         OutputFile_Text.contains(".gz",Qt::CaseInsensitive)||
         OutputFile_Text.contains(".Z",Qt::CaseInsensitive)||
-        OutputFile_Text.contains(QRegExp(".??o",Qt::CaseInsensitive))||
-        OutputFile_Text.contains(QRegExp(".??d",Qt::CaseInsensitive))||
-        OutputFile_Text.contains(QRegExp(".??n",Qt::CaseInsensitive))||
-        OutputFile_Text.contains(QRegExp(".??g",Qt::CaseInsensitive))){
+        OutputFile_Text.contains(QRegularExpression(".??o",QRegularExpression::CaseInsensitiveOption))||
+        OutputFile_Text.contains(QRegularExpression(".??d",QRegularExpression::CaseInsensitiveOption))||
+        OutputFile_Text.contains(QRegularExpression(".??n",QRegularExpression::CaseInsensitiveOption))||
+        OutputFile_Text.contains(QRegularExpression(".??g",QRegularExpression::CaseInsensitiveOption))){
         showmsg("error : invalid extension of output file (%s)",qPrintable(OutputFile_Text));
         return;
     }
@@ -945,8 +945,8 @@ int MainForm::GetOption(prcopt_t &prcopt, solopt_t &solopt,
     prcopt.elmaskhold=ElMaskHold*D2R;
     prcopt.thresslip=SlipThres;
     prcopt.maxtdiff =MaxAgeDiff;
-    prcopt.maxgdop  =RejectGdop;
-    prcopt.maxinno  =RejectThres;
+    //prcopt.maxgdop  =RejectGdop;
+    prcopt.maxinno[0]  =RejectThres;
     prcopt.outsingle=OutputSingle;
     if (BaseLineConst) {
         prcopt.baseline[0]=BaseLine[0];
@@ -1138,7 +1138,7 @@ gtime_t MainForm::GetTime1(void)
     QDateTime time(dateTime1->dateTime());
 
     gtime_t t;
-    t.time=time.toTime_t();t.sec=time.time().msec()/1000;
+    t.time=time.toSecsSinceEpoch();t.sec=time.time().msec()/1000;
 
     return t;
 }
@@ -1148,20 +1148,20 @@ gtime_t MainForm::GetTime2(void)
     QDateTime time(dateTime2->dateTime());
 
     gtime_t t;
-    t.time=time.toTime_t();t.sec=time.time().msec()/1000;
+    t.time=time.toSecsSinceEpoch();t.sec=time.time().msec()/1000;
 
     return t;
 }
 // set time to time-1 -------------------------------------------------------
 void MainForm::SetTime1(gtime_t time)
 {
-    QDateTime t=QDateTime::fromTime_t(time.time); t=t.addMSecs(time.sec*1000);
+    QDateTime t=QDateTime::fromSecsSinceEpoch(time.time); t=t.addMSecs(time.sec*1000);
     dateTime1->setDateTime(t);
 }
 // set time to time-2 -------------------------------------------------------
 void MainForm::SetTime2(gtime_t time)
 {
-    QDateTime t=QDateTime::fromTime_t(time.time); t=t.addMSecs(time.sec*1000);
+    QDateTime t=QDateTime::fromSecsSinceEpoch(time.time); t=t.addMSecs(time.sec*1000);
     dateTime2->setDateTime(t);
 }
 // update enable/disable of widgets -----------------------------------------
diff --git a/app/qtapp/rtkpost_qt/postopt.cpp b/app/qtapp/rtkpost_qt/postopt.cpp
index 483b8ae..b0eb394 100644
--- a/app/qtapp/rtkpost_qt/postopt.cpp
+++ b/app/qtapp/rtkpost_qt/postopt.cpp
@@ -715,8 +715,8 @@ void OptDialog::LoadOpt(const QString &file)
     ElMaskAR->setValue(prcopt.elmaskar * R2D);
     ElMaskHold->setValue(prcopt.elmaskhold * R2D);
     MaxAgeDiff->setValue(prcopt.maxtdiff);
-    RejectGdop->setValue(prcopt.maxgdop);
-    RejectThres->setValue(prcopt.maxinno);
+    //RejectGdop->setValue(prcopt.maxgdop);
+    RejectThres->setValue(prcopt.maxinno[0]);
     SlipThres->setValue(prcopt.thresslip);
     ARIter->setValue(prcopt.armaxiter);
     NumIter->setValue(prcopt.niter);
@@ -865,8 +865,8 @@ void OptDialog::SaveOpt(const QString &file)
     prcopt.elmaskar = ElMaskAR->value() * D2R;
     prcopt.elmaskhold = ElMaskHold->value() * D2R;
     prcopt.maxtdiff = MaxAgeDiff->value();
-    prcopt.maxgdop = RejectGdop->value();
-    prcopt.maxinno = RejectThres->value();
+    //prcopt.maxgdop = RejectGdop->value();
+    prcopt.maxinno[0] = RejectThres->value();
     prcopt.thresslip = SlipThres->value();
     prcopt.armaxiter = ARIter->value();
     prcopt.niter = NumIter->value();
diff --git a/app/qtapp/rtkpost_qt/rtkpost_qt.pro b/app/qtapp/rtkpost_qt/rtkpost_qt.pro
index 38864fd..cf9ff04 100644
--- a/app/qtapp/rtkpost_qt/rtkpost_qt.pro
+++ b/app/qtapp/rtkpost_qt/rtkpost_qt.pro
@@ -4,7 +4,7 @@
 #
 #-------------------------------------------------
 
-QT       += widgets core gui
+QT       += widgets core gui core5compat
 
 include(../qtapp.pri)
 
diff --git a/src/rtkcmn.c b/src/rtkcmn.c
index e559619..5364f2f 100644
--- a/src/rtkcmn.c
+++ b/src/rtkcmn.c
@@ -4045,8 +4045,8 @@ extern int rtk_uncompress(const char *file, char *uncfile)
     return stat;
 }
 /* dummy application functions for shared library ----------------------------*/
-#ifdef WIN_DLL
-extern int showmsg(char *format,...) {return 0;}
+#ifndef WIN_DLL
+extern int showmsg(const char *format,...) {return 0;}
 extern void settspan(gtime_t ts, gtime_t te) {}
 extern void settime(gtime_t time) {}
 #endif

```

It kept teasing me along and getting a little bit deeper, and when I got to `pthread_mutex_lock` errors, I stopped digging.

**Comment by drf5n** [comment]
I've got it working on a Mac at https://github.com/rtklibexplorer/RTKLIB/pull/138

**Comment by rtklibexplorer** [comment]
Compile errors fixed in commit on 4/17/23.  Note that the qt apps are still not supported and the user interfaces do not include many of the parameters used for new features in the demo5 code.
